apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: node-express
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: node-express
spec:
  params:
  - name: clusterbuilder
    value: standard-ubi-8
  source:
    git:
      url: https://github.com/David-VMware/nodejs.git
      ref:
        branch: main
